name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # استخدم نفس إصدار بايثون الذي تستخدمه محليًا

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc unixodbc-dev
          sudo apt-get install -y gcc g++

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$(pwd):$(pwd)/app" >> $GITHUB_ENV

      - name: Verify Environment
        run: |
          echo "Python Version: $(python --version)"
          echo "Installed Packages:"
          pip list
          echo "Current Directory: $(pwd)"
          echo "Directory Structure:"
          ls -R
          echo "PYTHONPATH: $PYTHONPATH"

      - name: Run Unittest (individual file execution)
        run: |
          python -m unittest tests.regression
          python -m unittest discover -s tests/unittests -p "*.py"

      - name: Run Pytest with Coverage
        run: pytest tests/ --cov=app --cov-report=term-missing --disable-warnings
